MOTD:
  - "Welcome to the server!"
  - "This is the MOTD"
  - "This is the MOTD"
  - "This is the MOTD"

Scoreboard:
  title: "&6&lServer"
  lines:
    - "test"
    - "test"

Server_Selector:
  Item_1:
    name: "&a&lServer 1"
    command: "joinqueue test1"
    slot: 13
    material: COMPASS
    amount: 1
    lore:
      - "&7Click to join"
      - "&7Server 1"
  Item_2:
    name: "&a&lServer 2"
    command: "joinqueue test2"
    slot: 15
    material: REDSTONE_BLOCK
    amount: 1
    lore:
      - "&7Click to join"
      - "&7Server 2"
  Item_3:
    name: "&a&lServer 3"
    command: "joinqueue test3"
    slot: 13
    material: EMERALD_BLOCK
    amount: 1
    lore:
      - "&7Click to join"
      - "&7Server 3"

Tablist:
  header: "&6&lServer"
  footer: "&6&lServer"
  lines:
    - "Line 1"
    - "Line 2"
    - "Line 3"
    - "Line 4"
    - "Line 5"
    - "Line 6"
    - "Line 7"
    - "Line 8"
    - "Line 9"
    - "Line 10"
    - "Line 11"
    - "Line 12"
    - "Line 13"
    - "Line 14"
    - "Line 15"
    - "Line 16"
    - "Line 17"
    - "Line 18"
    - "Line 19"
    - "Line 20"
    - "Line 21"
    - "Line 22"
    - "Line 23"
    - "Line 24"
    - "Line 25"
    - "Line 26"
    - "Line 27"
    - "Line 28"
    - "Line 29"
    - "Line 30"
    - "Line 31"
    - "Line 32"
    - "Line 33"
    - "Line 34"
    - "Line 35"
    - "Line 36"
    - "Line 37"
    - "Line 38"
    - "Line 39"
    - "Line 40"
    - "Line 41"
    - "Line 42"
    - "Line 43"
    - "Line 44"
    - "Line 45"
    - "Line 46"
    - "Line 47"
    - "Line 48"
    - "Line 49"
    - "Line 50"
    - "Line 51"
    - "Line 52"
    - "Line 53"
    - "Line 54"
    - "Line 55"
    - "Line 56"
    - "Line 57"
    - "Line 58"
    - "Line 59"
    - "Line 60"
    - "Line 61"
    - "Line 62"
    - "Line 63"
    - "Line 64"
    - "Line 65"
    - "Line 66"
    - "Line 67"
    - "Line 68"
    - "Line 69"
    - "Line 70"
    - "Line 71"
    - "Line 72"
    - "Line 73"
    - "Line 74"
    - "Line 75"
    - "Line 76"
    - "Line 77"
    - "Line 78"
    - "Line 79"
    - "Line 80"

# Items
#
# The items section defines the items that can be used in the game.
#
# Guide for "data". 0 -> EnderButt. 1 -> Server Selector. 2 -> Visibility

Inventory:
  Enderbutt:
    name: "&e&lEnderbutt"
    material: ENDER_PEARL
    amount: 1
    slot: 2
    enabled: true
    lore:
      - "&7&oRight click to throw"
      - "&7&oLeft click to eat"
      - "&7&oRight click to eat"
  Server_Selector:
    name: "&e&lServer Selector"
    material: COMPASS
    amount: 1
    slot: 4
    enabled: true
    lore:
      - "&7&oRight click to open"
      - "&7&oLeft click to eat"
      - "&7&oRight click to eat"
  Show_Players:
    name: "&e&lHide Players"
    material: GREEN_DYE
    amount: 1
    slot: 6
    enabled: true
    lore:
      - "&7&oRight click to open"
      - "&7&oLeft click to eat"
      - "&7&oRight click to eat"
  Hide_Players:
    name: "&e&lShow Players"
    material: GRAY_DYE
    amount: 1
    slot: 6
    lore:
      - "&7&oRight click to open"
      - "&7&oLeft click to eat"
      - "&7&oRight click to eat"